services:
  mongodb:
    image: mongo:latest
    container_name: mongo_home_harmony
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_home_harmony
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongo_data: {}
